package command

import (
	"bluebot/command/core"
	"bluebot/config"
	"log"
	"strings"

	"github.com/bwmarrin/discordgo"
)

var (
	// Opus encoding constants
	FrameSize      int    = 960
	Channels       int    = 1
	SampleRate     int    = 48000
	BitRate        int    = 64 * 1000
	VoiceSelection string = "bluebot"
)

/*
Set the current voice preset from the available ones
*/
func HandleSetVoice(session *discordgo.Session, msg *discordgo.MessageCreate, args []string) error {
	if len(args) < 1 {
		session.ChannelMessageSend(msg.ChannelID, "No voice preset given")
		return nil
	}
	if _, ok := config.VoicePresets[args[0]]; !ok {
		session.ChannelMessageSend(msg.ChannelID, "Preset doesn't exist")
		return nil
	}
	VoiceSelection = args[0]
	session.ChannelMessageSend(msg.ChannelID, "Preset set to "+VoiceSelection)
	return nil
}

/*
Play the MP3 audio file generated by the Python backend
*/
func HandleTell(session *discordgo.Session, msg *discordgo.MessageCreate, args []string) error {
	conn, err := core.GetActiveConnection(session, msg.GuildID, "", msg.Author.ID)
	if err != nil {
		log.Fatalln(err)
		session.ChannelMessageSend(msg.ChannelID, "You're not in a voice channel")
		return nil
	}
	return conn.SendEvent("greeter", strings.Join(args, " "), msg.ChannelID)
}
