AudioPath: /var/lib/bluebot/tmp
CivListPath: /var/lib/bluebot/civ_list.csv
CivSelections: 3
GoogleKeyPath: /etc/bluebot/google_token.json
DiscordTokenPath: /etc/bluebot/token.txt
ImageFontPath: /usr/share/fonts/truetype/freefont/FreeSans.ttf
ImagePath: /var/lib/bluebot/images 
ImageSettingsPath: /var/lib/bluebot/images.json
LogFilePath: /var/log/bluebot/logfile.log
SettingsDurationS: 300
VoicePresetsPath: /var/lib/bluebot/voice_presets.json 
